import * as swaggerJSDoc from "swagger-jsdoc";

const swaggerJsdoc = require('swagger-jsdoc');
const ss = require('../modules/groups/groups.routes');

const options = {
  // List of files to be processes. You can also set globs './routes/*.js'
  apis: ['./src/modules/**/*.ts'],
  basePath: '/',
  swaggerDefinition: {
    info: {
      description: 'Test API with autogenerated swagger doc',
      swagger: '2.0',
      title: 'Dessert API',
      version: '1.0.0',
    },
  },
};

const specs:swaggerJSDoc.Options = swaggerJsdoc(options);
export default specs;
